language: cpp

compiler:
  - gcc
  - clang

env:
  - CONFIGURATION=Debug
  - CONFIGURATION=Release

script:
  - env
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE:STRING=${CONFIGURATION} ..
  - make
