version: '{build}'

skip_tags: true

install: []

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

build_script:
  - md build
  - cd build
  - if "%PLATFORM%"=="x64" cmake -G "Visual Studio 12 Win64" ..
  - if "%PLATFORM%"=="Win32" cmake -G "Visual Studio 12" ..
  - msbuild /m /p:Configuration="%CONFIGURATION%" /p:Platform="%PLATFORM%" utf8.sln
