version: '{build}'

skip_tags: true

install: []

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

build_script:
  - md build
  - cd build
  - cmake -G "Visual Studio 12" ..
  - msbuild /m /p:Configuration="%CONFIGURATION%" /p:Platform="%PLATFORM%" utf8.sln
